#ifndef APP_NAV_H
#define APP_NAV_H

//// ENUM

typedef enum {
    APP_NAV_STATE_MENU = 0,
    APP_NAV_STATE_GAME_EXEC,
    APP_NAV_STATE_RECORDS,
    APP_NAV_STATE_SETTINGS,
    APP_NAV_STATE_FINISH
} APP_NAV_STATE;

#endif
