#ifndef GAME_EXEC_H
#define GAME_EXEC_H
#include <stdbool.h>

#include "AppNav.h"
#include "GameController.h"

//// ENUM

typedef enum {
    GAME_EXEC_USER_ACTION_NONE = 0,
    GAME_EXEC_USER_ACTION_DOWN_KEYUP,
    GAME_EXEC_USER_ACTION_UP_KEYUP,
    GAME_EXEC_USER_ACTION_LEFT_KEYUP,
    GAME_EXEC_USER_ACTION_RIGHT_KEYUP,
    GAME_EXEC_USER_ACTION_SPACEBAR_KEYUP,
    GAME_EXEC_USER_ACTION_SPACEBAR_KEYDOWN,
    GAME_EXEC_USER_ACTION_DOWN_KEYDOWN,
    GAME_EXEC_USER_ACTION_UP_KEYDOWN,
    GAME_EXEC_USER_ACTION_LEFT_KEYDOWN,
    GAME_EXEC_USER_ACTION_RIGHT_KEYDOWN,
    GAME_EXEC_USER_ACTION_PAUSE

} GAME_EXEC_USER_ACTION;

//// EXTERNAL FUNCTION DECLARATION

bool is_game_paused();
void reset_game_exec();
void finish_game_exec();

APP_NAV_STATE handle_game_exec_timer();
APP_NAV_STATE handle_game_exec_event(GAME_EXEC_USER_ACTION action);

#endif
